<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../PascalCockpit.Contracts/PascalCockpit.Contracts.csproj" />
    <ProjectReference Include="../PascalCockpit.Normalization/PascalCockpit.Normalization.csproj" />
  </ItemGroup>
</Project>
