namespace PascalCockpit.Views;

public enum UiLang
{
    Zh,
    En
}

/// <summary>
/// Local consumer copy. One semantic path; Chinese is composed first, English is
/// the same facts through this table. No network or model translation.
/// </summary>
public static class ConsumerCopy
{
    public static UiLang Parse(string? raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return UiLang.Zh;
        var t = raw.Trim();
        if (t.Equals("en", StringComparison.OrdinalIgnoreCase)
            || t.Equals("en-US", StringComparison.OrdinalIgnoreCase)
            || t.Equals("english", StringComparison.OrdinalIgnoreCase)
            || t.Equals("en_us", StringComparison.OrdinalIgnoreCase))
        {
            return UiLang.En;
        }

        if (t.Equals("zh", StringComparison.OrdinalIgnoreCase)
            || t.Equals("zh-CN", StringComparison.OrdinalIgnoreCase)
            || t.Equals("zh_cn", StringComparison.OrdinalIgnoreCase)
            || t.Equals("chinese", StringComparison.OrdinalIgnoreCase)
            || t.Equals("中文", StringComparison.Ordinal))
        {
            return UiLang.Zh;
        }

        return UiLang.Zh;
    }

    public static string Code(UiLang lang) => lang == UiLang.En ? "en" : "zh";

    public static string T(UiLang lang, string key) =>
        lang == UiLang.En
            ? (EnChrome.TryGetValue(key, out var en) ? en : key)
            : (ZhChrome.TryGetValue(key, out var zh) ? zh : key);

    public static string L(UiLang lang, string zh, string en) => lang == UiLang.En ? en : zh;

    public static string Localize(string text, UiLang lang)
    {
        if (lang != UiLang.En || string.IsNullOrEmpty(text)) return text;
        var s = text;
        foreach (var (zh, en) in Fragments)
        {
            if (s.Contains(zh, StringComparison.Ordinal))
                s = s.Replace(zh, en, StringComparison.Ordinal);
        }

        return s.Replace("。", ". ", StringComparison.Ordinal)
            .Replace("；", "; ", StringComparison.Ordinal)
            .Replace("：", ": ", StringComparison.Ordinal);
    }

    static readonly Dictionary<string, string> ZhChrome = new(StringComparer.Ordinal)
    {
        ["hud_title"] = "驾驶舱 HUD",
        ["collect_at"] = "采集时间：",
        ["quality"] = "快照质量：",
        ["show_history"] = "显示历史与暂停",
        ["hide_history"] = "只看当前任务",
        ["pascal_n"] = "待你决定 {0} 项",
        ["refresh"] = "刷新",
        ["copy_summary"] = "复制摘要",
        ["refresh_tip"] = "后台刷新，不抢焦点",
        ["copy_summary_tip"] = "复制求助摘要，不外发",
        ["topmost"] = "置顶",
        ["untopmost"] = "取消置顶",
        ["expand"] = "展开",
        ["collapse"] = "收起",
        ["copy_id"] = "复制目标 ID",
        ["lang_zh"] = "中文",
        ["lang_en"] = "English",
        ["wait_first"] = "等待首次刷新。",
        ["copied_summary"] = "已复制摘要。未外发。",
        ["copied_id"] = "已复制目标 ID，并未打开该任务。",
        ["clipboard_fail"] = "无法写入剪贴板：",
        ["refresh_fail_keep"] = "刷新显示失败，已保留窗口。",
        ["refresh_fail_kept"] = "刷新失败，保留上次已知。",
        ["refresh_fail_none"] = "刷新失败，无上次快照。",
        ["refresh_no_snap"] = "已刷新，但本轮没有快照。",
        ["now"] = "现在",
        ["how_far"] = "做到哪",
        ["stuck"] = "卡在哪",
        ["next"] = "下一步谁处理",
        ["need_you"] = "要不要你处理",
        ["goal"] = "目标",
        ["progress"] = "进度（仅在有可靠依据时显示）",
        ["pascal_section"] = "待你决定",
        ["diag_open"] = "查看技术诊断",
        ["diag_close"] = "收起技术诊断",
        ["current_work"] = "当前工作（并发）",
        ["no_current_work"] = "无当前工作项。",
        ["current_roles"] = "当前角色",
        ["no_current_roles"] = "无当前角色项。",
        ["history_roles"] = "历史角色（可追溯，非当前）",
        ["role_lead"] = "负责人",
        ["role_executor_n"] = "执行 {0}",
        ["role_reviewer_n"] = "审核 {0}",
        ["role_legion_n"] = "军团 {0}",
        ["not_obtained"] = "未获取",
        ["review_not_assigned"] = "未安排审核",
        ["work_label"] = "工作：",
        ["model_label"] = "模型：",
        ["effort_label"] = "effort：",
        ["roles_section"] = "当前角色：",
        ["history_roles_section"] = "历史角色：",
        ["artifacts"] = "成果",
        ["no_artifacts"] = "无成果条目。",
        ["lead_pending"] = "原负责人待处理",
        ["secretary"] = "秘书关注",
        ["history_section"] = "历史 / 上次已知（可追溯，非当前故障）",
        ["history_item"] = "历史条目",
        ["no_history"] = "无历史/上次已知条目。",
        ["nav"] = "导航（仅快照已有目标）",
        ["no_nav"] = "无可用导航目标。",
        ["fact_time"] = "事实时间：",
        ["quality_short"] = "质量：",
        ["summary_title"] = "摘要（Pascal Cockpit）",
        ["summary_note"] = "说明：以下仅复述当前快照已有事实，不宣布通过或完成。",
        ["summary_current_n"] = "当前任务数：",
        ["summary_issues"] = "来源问题（诊断原文）：",
        ["no_snapshot"] = "当前没有可用快照。",
        ["no_projects"] = "当前快照没有项目实体。",
        ["details_host"] = "详情",
        ["empty_projects"] = "暂无项目。",
        ["summary_help_title"] = "求助摘要（Pascal Cockpit）",
        ["recipient"] = "接收者：",
        ["recipient_blank"] = "（未指定，复制后自行填写）",
        ["pending_section"] = "待处理：",
        ["evidence_section"] = "关键证据：",
        ["project_label"] = "项目：",
        ["phase_label"] = "阶段：",
        ["current_desc"] = "当前说明：",
        ["next_label"] = "下一步：",
        ["project_quality"] = "项目质量：",
        ["last_fact"] = "最近事实时间：",
        ["owner_pascal"] = "待 Pascal",
        ["owner_lead"] = "待原 Lead",
        ["owner_secretary"] = "秘书关注",
        ["owner_none"] = "无",
        ["none"] = "无",
        ["fact_time_eq"] = "事实时间=",
        ["quality_eq"] = "质量=",
        ["verify_n"] = "状态待核实数：",
        ["hist_n"] = "历史与暂停：",
        ["who_label"] = "现在：",
        ["how_far_label"] = "做到哪：",
        ["stuck_label"] = "卡在哪：",
        ["need_you_label"] = "要不要你处理：",
        ["blank"] = "（未声明）"
    };

    static readonly Dictionary<string, string> EnChrome = new(StringComparer.Ordinal)
    {
        ["hud_title"] = "Cockpit HUD",
        ["collect_at"] = "Collected: ",
        ["quality"] = "Snapshot quality: ",
        ["show_history"] = "Show history and paused",
        ["hide_history"] = "Current tasks only",
        ["pascal_n"] = "{0} item(s) need your decision",
        ["refresh"] = "Refresh",
        ["copy_summary"] = "Copy summary",
        ["refresh_tip"] = "Refresh in the background; does not steal focus",
        ["copy_summary_tip"] = "Copy the help summary; do not send it",
        ["topmost"] = "Always on top",
        ["untopmost"] = "Unpin",
        ["expand"] = "Expand",
        ["collapse"] = "Collapse",
        ["copy_id"] = "Copy target ID",
        ["lang_zh"] = "中文",
        ["lang_en"] = "English",
        ["wait_first"] = "Waiting for the first refresh.",
        ["copied_summary"] = "Summary copied. Not sent.",
        ["copied_id"] = "Target ID copied. The task was not opened.",
        ["clipboard_fail"] = "Could not write the clipboard: ",
        ["refresh_fail_keep"] = "Refresh display failed; the window was kept. ",
        ["refresh_fail_kept"] = "Refresh failed; last known state was kept.",
        ["refresh_fail_none"] = "Refresh failed; no previous snapshot.",
        ["refresh_no_snap"] = "Refreshed, but this round has no snapshot.",
        ["now"] = "Now",
        ["how_far"] = "How far",
        ["stuck"] = "Where it is stuck",
        ["next"] = "Who acts next",
        ["need_you"] = "Do you need to act",
        ["goal"] = "Goal",
        ["progress"] = "Progress (only when a reliable basis exists)",
        ["pascal_section"] = "Needs your decision",
        ["diag_open"] = "Show technical diagnostics",
        ["diag_close"] = "Hide technical diagnostics",
        ["current_work"] = "Current work (concurrent)",
        ["no_current_work"] = "No current work items.",
        ["current_roles"] = "Current roles",
        ["no_current_roles"] = "No current role items.",
        ["history_roles"] = "Historical roles (traceable, not current)",
        ["role_lead"] = "Owner",
        ["role_executor_n"] = "Executor {0}",
        ["role_reviewer_n"] = "Reviewer {0}",
        ["role_legion_n"] = "Army {0}",
        ["not_obtained"] = "not obtained",
        ["review_not_assigned"] = "No reviewer assigned",
        ["work_label"] = "Work: ",
        ["model_label"] = "Model: ",
        ["effort_label"] = "effort: ",
        ["roles_section"] = "Current roles:",
        ["history_roles_section"] = "Historical roles:",
        ["artifacts"] = "Outputs",
        ["no_artifacts"] = "No output entries.",
        ["lead_pending"] = "Waiting on the original owner",
        ["secretary"] = "Secretary watching",
        ["history_section"] = "History / last known (traceable, not a current fault)",
        ["history_item"] = "History entry",
        ["no_history"] = "No history / last-known entries.",
        ["nav"] = "Navigation (snapshot targets only)",
        ["no_nav"] = "No navigation targets.",
        ["fact_time"] = "Fact time: ",
        ["quality_short"] = "Quality: ",
        ["summary_title"] = "Summary (Pascal Cockpit)",
        ["summary_note"] = "Note: this only restates facts already in the snapshot. It does not declare pass or completion.",
        ["summary_current_n"] = "Current tasks: ",
        ["summary_issues"] = "Source issues (raw diagnostics):",
        ["no_snapshot"] = "No snapshot is available.",
        ["no_projects"] = "This snapshot has no project entities.",
        ["details_host"] = "Details",
        ["empty_projects"] = "No projects.",
        ["summary_help_title"] = "Help summary (Pascal Cockpit)",
        ["recipient"] = "Recipient: ",
        ["recipient_blank"] = "(unspecified; fill in after copy)",
        ["pending_section"] = "Pending:",
        ["evidence_section"] = "Key evidence:",
        ["project_label"] = "Project: ",
        ["phase_label"] = "Phase: ",
        ["current_desc"] = "Current description: ",
        ["next_label"] = "Next: ",
        ["project_quality"] = "Project quality: ",
        ["last_fact"] = "Latest fact time: ",
        ["owner_pascal"] = "waiting on Pascal",
        ["owner_lead"] = "waiting on original owner",
        ["owner_secretary"] = "secretary watching",
        ["owner_none"] = "none",
        ["none"] = "none",
        ["fact_time_eq"] = "fact time=",
        ["quality_eq"] = "quality=",
        ["verify_n"] = "Status to verify: ",
        ["hist_n"] = "History and paused: ",
        ["who_label"] = "Now: ",
        ["how_far_label"] = "How far: ",
        ["stuck_label"] = "Where it is stuck: ",
        ["need_you_label"] = "Do you need to act: ",
        ["blank"] = "(not stated)"
    };

    static (string Zh, string En)[] OrderLongestFirst((string Zh, string En)[] items) =>
        items.OrderByDescending(x => x.Zh.Length).ThenByDescending(x => x.Zh, StringComparer.Ordinal).ToArray();

    // Source table; Fragments is longest-first so nested phrases win.
    static readonly (string Zh, string En)[] RawFragments =
    {
        ("原执行者继续生成与退修，已到第", "Original executor continues generation and repair, reached day "),
        ("天，完成后负责人验收", "; owner accepts when it is done"),
        ("原负责人继续验收", "The original owner continues acceptance"),
        ("负责人继续验收", "the owner continues acceptance"),
        ("已处理待修复：原Lead已给出失败/返修结论", "Handled pending repair: original owner already gave a fail/repair conclusion"),
        ("已处理：原Lead已给出部分采用或处理结论", "Handled: original owner already gave a partial-adoption or handling conclusion"),
        ("已处理：原负责人已给出部分采用或处理结论", "Handled: original owner already gave a partial-adoption or handling conclusion"),
        ("原Lead已给出部分采用或处理结论", "original owner already gave a partial-adoption or handling conclusion"),
        ("原负责人已给出部分采用或处理结论", "original owner already gave a partial-adoption or handling conclusion"),
        ("原Lead", "original owner"),
        ("原Lead已给出失败/返修结论", "original owner already gave a fail/repair conclusion"),
        (" 条，不影响当前业务判断", " item(s); does not affect current business judgment"),
        ("原执行者继续生成与退修，", "Original executor continues generation and repair, "),
        ("当前负责人按最新回执处理", "Current owner is handling the latest receipt"),
        ("当前必要身份无法确认", "the required current identity cannot be confirmed"),
        ("不能确认本轮执行所依据的身份", "cannot confirm the identity this round's execution relies on"),
        ("结果已交回，负责人已判退修；后续处理被平台限制中断，退修尚未派出", "Result returned; owner already asked for repair; follow-up was interrupted by a platform limit, and the repair has not been sent"),
        ("结果已交回；负责人已判退修，原执行者正在按退修继续做", "Result returned; owner asked for repair, and the original executor is working on it"),
        ("退修已派出，等待本轮结果", "Repair dispatched; waiting for this round's result"),
        ("等待本轮结果交回后负责人处理", "Wait for this round's result, then the owner handles it"),
        ("准备退修续接", "Preparing the repair follow-up"),
        ("执行已验收，整体尚未通过", "Executors accepted; the whole comparison is not a product pass"),
        ("结果已交回；负责人验收发现问题，需要原执行者退修", "Result returned; owner found problems and needs the original executor to repair"),
        ("已处理（额度失败，资源已另派）；内容未验收", "Handled (quota failed, work reassigned); content not accepted"),
        ("原执行者继续生成与退修，本轮还没交回，完成后负责人验收", "Original executor is still generating and repairing; this round is not returned yet; owner accepts when it is done"),
        ("按当前源处理平台反馈后接原负责人", "Handle the platform feedback from the current source, then the original owner continues"),
        ("未明确谁发起平台反馈，不能保证无需你处理", "Who should start the platform feedback is unspecified; it is not guaranteed that you can ignore it"),
        ("本轮还没交回，不能当成已经交付", "This round is not returned yet, so it is not delivered"),
        ("已有文件已存在但暂不能读取这些状态，影响：不能从该文件补充当前状态", "A file exists but these states cannot be read from it yet, so it cannot fill in current status"),
        ("有文件已存在但暂不能读取这些状态，影响：不能从该文件补充当前状态", "A file exists but these states cannot be read from it yet, so it cannot fill in current status"),
        ("实际发出操作前做授权检查", "authorization check before the actual write"),
        ("确认与原有修正方式是否兼容", "confirm compatibility with the existing correction"),
        ("已确认的输出和界面成果保留", "accepted output and UI results are kept"),
        ("原执行者只修检查的先后顺序；交回后，原负责人继续验收", "Original executor is only fixing check order; after return, the original owner continues acceptance"),
        ("原执行者只修检查的先后顺序", "Original executor is only fixing check order"),
        ("交回后，原负责人继续验收", "After return, the original owner continues acceptance"),
        ("原负责人接着验收", "The original owner now continues acceptance"),
        ("原负责人正在验收", "The original owner is accepting now"),
        ("交回后由负责人验收", "After return, the owner accepts"),
        ("负责人接着验收", "The owner continues acceptance"),
        ("具体检查事项还未说明", "Specific remaining checks are not yet described"),
        ("已确认的成果保留", "Accepted results are kept"),
        ("只修检查的先后顺序", "only fix check order"),
        ("做授权检查", "do an authorization check"),
        ("目前没有已知阻点", "No known blocker right now"),
        ("当前执行失败，该项未被其他在飞工作覆盖", "this item failed and is not covered by other in-flight work"),
        ("当前失败，不能被其他执行中工作盖住", "failed; other in-flight work must not hide this"),
        ("验收后待派出退修", "Accepted as repair; not dispatched yet"),
        ("已派出退修", "Repair dispatched"),
        ("故障/部分异常", "Fault / partial exception"),
        ("正常推进", "Moving normally"),
        ("等待验收", "Waiting for acceptance"),
        ("等待结果", "Waiting for a result"),
        ("需要你处理", "Needs your action"),
        ("状态待核实", "Status not yet confirmed"),
        ("已完成", "Completed"),
        ("已暂停", "Paused"),
        ("项目已结束；结果可在历史中查看", "The project has ended; results are in history"),
        ("项目已暂停", "The project is paused"),
        ("当前有需要你决定的事项", "There is a decision that needs you"),
        ("缺少足够来源", "Not enough source"),
        ("由原负责人处理", "the original owner handles it"),
        ("正在验收", "Accepting now"),
        ("验收发现问题，等待退修", "Acceptance found problems; waiting for repair"),
        ("等待执行者交回", "Waiting for executors to return"),
        ("等待负责人处理", "Waiting for the owner to handle it"),
        ("结果已交回，等待负责人处理", "Result returned; waiting for the owner to handle it"),
        ("已验收", "Accepted"),
        ("已安排审核；当前状态未获取", "Reviewer assigned; current state not obtained"),
        ("正在审核", "Reviewing"),
        ("内容未验收", "Content not accepted"),
        ("已安排审核", "Reviewer assigned"),
        ("规划中", "Planning"),
        ("未获取", "not obtained"),
        ("未安排审核", "No reviewer assigned"),
        ("当前角色", "Current roles"),
        ("历史角色（可追溯，非当前）", "Historical roles (traceable, not current)"),
        ("负责人", "Owner"),
        ("本轮还在做，还没交回", "Still in progress this round; not returned yet"),
        ("结果已经交回，负责人正在验收", "Result already returned; owner is accepting"),
        ("结果已经交回，负责人已判退修", "Result already returned; owner asked for repair"),
        ("结果已经交回", "Result already returned"),
        ("负责人正在验收，还没有新的终态", "Owner is accepting; there is no new final result yet"),
        ("后续处理被平台限制中断，退修尚未派出", "Follow-up was interrupted by a platform limit; repair has not been sent"),
        ("退修已派出，原执行者正在按退修继续做", "Repair was sent; original executor is working on it"),
        ("卡在验收发现的问题上，需要原执行者退修", "Stuck on problems found in acceptance; original executor must repair"),
        ("当前执行失败，待处理", "Current execution failed; waiting to be handled"),
        ("无法判断卡点的具体部分：缺少足够来源", "Cannot judge the blocker: not enough source"),
        ("现在不需要你处理", "You do not need to act now"),
        ("需要你决定", "Needs your decision"),
        ("原执行者正在做，本轮还没交回", "Original executor is working; this round is not returned yet"),
        ("原执行者继续生成，交回后负责人验收", "Original executor continues generation; owner accepts after return"),
        ("原执行者继续生成，完成后负责人验收", "Original executor continues generation; owner accepts when it is done"),
        ("原执行者继续生成", "Original executor continues generation"),
        ("原执行者继续做，完成后负责人验收", "Original executor continues; owner accepts when it is done"),
        ("原执行者正在按退修继续做", "Original executor is continuing the repair"),
        ("完成后负责人验收", "owner accepts when it is done"),
        ("结果已交回，负责人正在验收", "Result returned; owner is accepting now"),
        ("结果已交回，等待负责人验收", "Result returned; waiting for owner acceptance"),
        ("已处理（额度失败）；内容未验收", "Handled (quota failed); content not accepted"),
        ("已处理（部分采用）", "Handled (partially adopted)"),
        ("已接受并已采用", "Accepted and adopted"),
        ("回叫已发生，待原Lead处理", "Callback happened; waiting for the original owner"),
        ("历史来源缺口", "Historical source gaps"),
        ("不影响当前业务判断", "does not affect current business judgment"),
        ("状态待核实", "status to verify"),
        ("当前业务=", "current tasks="),
        ("历史与暂停=", "history and paused="),
        ("历史与暂停（", "history and paused ("),
        ("暂停/历史=", "history and paused="),
        ("暂停/历史 ", "history and paused "),
        ("当前缺口=", "status to verify="),
        ("当前来源缺口", "status to verify"),
        ("来源可读", "sources readable"),
        ("沿用上次已知（非本轮新鲜采集）", "using last known (not freshly collected this round)"),
        ("来源不可用或缺失", "source unavailable or missing"),
        ("来源冲突，结论待核实", "sources conflict; conclusion to verify"),
        ("来源状态未知", "source status unknown"),
        ("新鲜", "fresh"),
        ("历史/上次已知", "history / last known"),
        ("不可用", "unavailable"),
        ("冲突", "conflict"),
        ("未知", "unknown"),
        ("待你决定", "needs your decision"),
        ("秘书关注", "secretary watching"),
        ("原Lead待处理", "waiting on original owner"),
        ("无指定负责人", "no assigned owner"),
        ("未声明", "not stated"),
        ("未用一句话写明目标", "no one-line goal"),
        ("主动暂停", "paused on purpose"),
        ("来源不可用", "source unavailable"),
        ("来源冲突，待核实", "sources conflict; to verify"),
        ("已刷新 ", "Refreshed "),
        ("另有 ", "Also "),
        (" 份军团贡献待处理", " army contribution(s) waiting"),
        (" 份军团贡献已接受", " army contribution(s) accepted"),
        (" 份军团贡献已采用", " army contribution(s) adopted"),
        (" 份军团贡献", " army contribution(s)"),
        ("原Lead待处理/待验收 ", "original owner waiting/acceptance "),
        (" 条历史记录可追溯", " historical record(s) to trace"),
        ("暂无更细当前事实", "no finer current fact"),
        ("已处理", "Handled"),
        ("已接受", "Accepted"),
        ("已采用贡献", "Contribution adopted"),
        ("待验收", "Waiting for acceptance"),
        ("执行中", "in progress"),
        ("回合已结束 · 进程仍存活", "turn ended · process still alive"),
        ("结果已交回", "Result returned"),
        ("沿用上次已知，不是这一轮刚采到的。", "Using last known, not freshly collected this round."),
        ("快照来源不可用：请查看来源问题，勿当作全部正常。", "Snapshot source unavailable: check source issues; do not treat as all-normal."),
        ("快照存在来源冲突：请展开详情核实，勿当作全部正常。", "Snapshot sources conflict: open details to verify; do not treat as all-normal."),
        ("当前展示为上次已知状态，非本轮新鲜采集。", "Showing last known state, not a fresh collection this round."),
        ("本轮快照没有项目。", "This snapshot has no projects."),
        ("当前没有进行中的任务。暂停和历史可按需查看。", "No tasks in progress. History and paused items can be shown on demand."),
        ("暂无快照。等待采集结果。", "No snapshot yet. Waiting for collection."),
        ("尚未采集", "Not collected yet"),
        ("无快照", "No snapshot"),
        ("处理者未指定", "handler unspecified"),
        ("影响：", "impact: "),
        ("该项判断暂缺", "that judgment is unavailable"),
        ("不能把本轮显示成已交付", "cannot show this round as delivered"),
        ("不能把本轮显示成已交回", "cannot show this round as returned"),
        ("本轮验收结论以已读到的文件为准", "this round's acceptance follows files already read"),
        ("尚未交回或尚未产出", "not yet returned or not yet produced"),
        ("尚未产出", "not yet produced"),
        ("尚未交回", "not yet returned"),
        ("来源冲突：", "Source conflict: "),
        ("原执行者。", "Original executor. "),
        ("原负责人。", "Original owner. "),
        ("原执行者", "Original executor"),
        ("原负责人", "original owner"),
        ("负责人", "owner"),
        ("交回后，", "After return, "),
        ("交回后", "after return"),
        ("选中项目已不在当前快照中。", "The selected project is no longer in this snapshot."),
        ("暂无快照。", "No snapshot yet."),
        ("暂无项目。", "No projects."),
        ("目前没有更细的进度数字", "No finer progress number yet"),
        ("当前负责人按最新回执处理", "Current owner is handling the latest receipt"),
        ("正在处理，细节见上面几句", "In progress; details are in the lines above"),
        ("按最新结论继续", "Continue from the latest conclusion"),
        ("原执行者退修", "Original executor repairs"),
        ("负责人验收", "Owner acceptance"),
        ("历史/上次已知（非当前故障）", "history / last known (not a current fault)"),
        ("未声明角色", "role not stated"),
        ("没有导航目标。", "No navigation target."),
        ("目标不在当前快照已绑定实体上，已拒绝。", "Target is not bound on the current snapshot; refused."),
        ("拒绝未知 URL 协议或不一致对象。", "Unknown URL protocol or inconsistent object refused."),
        ("当前不支持直接打开该 Codex 任务。可复制原 ID，不要当作已打开。", "Direct open of that Codex task is not supported. You can copy the original ID; do not treat it as opened."),
        ("不支持的导航类型：", "Unsupported navigation kind: "),
        ("。可复制原目标。", ". You can copy the original target."),
        ("本地文件路径无效，未打开。", "Local file path is invalid; not opened."),
        ("本地路径不存在，未打开：", "Local path does not exist; not opened: "),
        ("当前操作系统无法打开本地文件。", "This OS cannot open local files."),
        ("未能启动关联程序，未伪造成功。", "Could not start the associated program; success was not faked."),
        ("打开本地文件失败：", "Failed to open the local file: "),
        ("已请求打开本地文件。", "Requested to open the local file."),
        ("宿主已持有同一快照（项目 ", "Host already holds the same snapshot (projects "),
        (" 刷新与历史入口使用同一 Snapshot，App 不重判状态。", " Refresh and history use the same Snapshot; the app does not re-judge status."),
        ("本轮回执尚未交回", "this-round receipt not yet returned"),
        ("本轮执行回执尚未交回", "this-round execution receipt not yet returned"),
        ("本轮结果文件尚未产出", "this-round result file not yet produced"),
        ("本轮验收结论", "this-round acceptance result"),
        ("本轮验收方式", "this-round acceptance method"),
        ("本轮执行回执", "this-round execution receipt"),
        ("本轮结果文件", "this-round result file"),
        ("本轮回执", "this-round receipt"),
        ("生成心跳", "generation heartbeat"),
        ("当前生成配置", "current generation config"),
        ("一项来源", "a source"),
        (" 条状态待核实", " status-to-verify item(s)"),
        ("等共 ", "; "),
        ("处理者：", "handler: "),
        ("世界已生成天数", "world days generated"),
        ("已到第", "reached day "),
        ("天 / 目标", " / target "),
        ("天（依据：", " (basis: "),
        (" 条历史记录可追溯", " historical record(s) to trace"),
        ("小世界", "Small World"),
        ("当前  ", "current "),
        ("当前 ", "current ")
    };

    static readonly (string Zh, string En)[] Fragments = OrderLongestFirst(RawFragments);
}
